"""Risk-tiered capability groups resolved by generated agents at runtime.

The package name remains ``toolkits`` so agents generated by older Studio releases keep
working.  The public product/API term is ``capabilities``.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import import_module
from typing import Any


@dataclass(frozen=True)
class CapabilitySpec:
    """One selectable capability and the minimum access policy it requires."""

    name: str
    label: str
    tier: int
    trust: str
    module: str
    hint: str


SPECS: tuple[CapabilitySpec, ...] = (
    CapabilitySpec("utility", "Utility", 0, "open", "utility", "math, time and deterministic utility helpers"),
    CapabilitySpec("web", "Web fetch", 0, "open", "web", "fetching web pages from public URLs"),
    CapabilitySpec("image", "Image", 0, "open", "image", "generating small demo images"),
    CapabilitySpec("files", "File reading", 1, "careful", "files", "reading and searching local files"),
    CapabilitySpec("file-write", "File editing", 2, "strict", "file_write", "creating and editing local files"),
    CapabilitySpec("shell", "Shell", 2, "strict", "shell", "running shell commands with approval"),
    CapabilitySpec("browser", "Browser", 2, "strict", "browser", "controlling a local browser"),
)

CATALOG: dict[str, CapabilitySpec] = {spec.name: spec for spec in SPECS}
NAMES: tuple[str, ...] = tuple(CATALOG)

HINTS: dict[str, str] = {spec.name: spec.hint for spec in SPECS}

PROMPT_GUIDES: dict[str, str] = {
    "files": """### Local file reading
- Use glob to find files by name, grep to search their contents, and read_file for the exact file.
- Read only what the request needs and never imply that a file was inspected unless the tool returned it.""",
    "file-write": """### Local file editing
- Read an existing file before changing it. Use edit or multi_edit for precise changes and write for new files.
- Preserve surrounding style, keep changes scoped to the request, and report a write only after the tool confirms it.
- File operations are not workspace-sandboxed yet, so treat every path as sensitive and avoid unrelated files.""",
    "shell": """### Shell commands
- Prefer the dedicated file tools for reading, searching and writing files; use bash for commands that need a shell.
- Quote paths containing spaces and keep commands narrowly scoped. Side-effecting commands require explicit approval.
- Never claim a command succeeded unless its output and exit status confirm it.""",
    "browser": """### Browser control
- Inspect the visible page before acting, use the smallest reliable interaction, and verify the resulting page state.
- Never claim navigation, submission or login succeeded unless the browser result confirms it.
- Do not ask the browser tool to wait for manual login; ask the user in chat when human action is required.""",
}


def validate(names: list[str]) -> list[str]:
    """Dedupe and order selections; full file editing supersedes read-only files."""
    unknown = sorted(set(names) - set(NAMES))
    if unknown:
        raise ValueError(f"unknown capabilities: {', '.join(unknown)} (available: {', '.join(NAMES)})")
    selected = set(names)
    if "file-write" in selected:
        selected.discard("files")
    return [name for name in NAMES if name in selected]


def required_trust(names: list[str]) -> str:
    """Return the minimum trust level forced by the highest selected risk tier."""
    selected = validate(names)
    tier = max((CATALOG[name].tier for name in selected), default=0)
    return ("open", "careful", "strict")[tier]


def requires_invite(names: list[str]) -> bool:
    """Sensitive and dangerous capabilities are never exposed without onboarding."""
    return required_trust(names) != "open"


def prompt_guides(names: list[str]) -> str:
    """Capability-specific operating guidance appended to the generated system prompt."""
    return "\n\n".join(PROMPT_GUIDES[name] for name in validate(names) if name in PROMPT_GUIDES)


def resolve(names: list[str]) -> tuple[list[Any], list[Any]]:
    """Build tools/plugins for selected capabilities without duplicate plugin bundles."""
    tools: list[Any] = []
    plugins: list[Any] = []
    for name in validate(names):
        module = import_module(f".{CATALOG[name].module}", __package__)
        tools.extend(module.tools())
        for plugin in module.plugins():
            if not any(plugin is existing for existing in plugins):
                plugins.append(plugin)
    return tools, plugins
